<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="">

    <link rel="stylesheet" href="../static/fonts/14362.ttf">
    <script src="https://kit.fontawesome.com/074becbd45.js" crossorigin="anonymous"></script>
    <title>Sushi</title>
</head>
<body class="body">
<header class="container">
    <div class="header">

        <div class="card" style="width: 18rem; text-align: center; background: inherit; border: none">
            <div class="card-body">
                <div class="logo"><img src="../static/images/logo.svg" alt="logo"></div>
            </div>
        </div>
        <!--        Bishkek-->
        <div class="card" style="width: 18rem; text-align: center; background: inherit; border: none">
            <div class="card-body">
                <div class="tel-head">
                    <div class="city"><h5 class="card-title cities">Бишкек</h5>
                    </div>
                    <div class="icon"><a href="https://wa.me/996502082222"><i class="fab fa-whatsapp icons"></i></a>
                    </div>
                </div>
                <div class="tel">
                    <div class="code">
                        <a href="tel:+996554082222">0 554/</a>
                        <a href="tel:+996774082222">0 774/</a>
                        <a href="tel:+996502082222">0 502</a>
                    </div>
                    <div class="number"><a href="tel:+996502082222">
                            08-22-22</a></div>
                </div>
            </div>
        </div>

        <!--        Osh-->
        <div class="card" style="width: 18rem; text-align: center; background: inherit; border: none">
            <div class="card-body">
                <div class="tel-head">
                    <div class="city"><h5 class="card-title cities">Ош</h5>
                    </div>
                    <div class="icon"><a href="https://wa.me/996556081111"><i class="fab fa-whatsapp icons"></i></a>
                    </div>
                </div>
                <div class="tel">
                    <div class="code">
                        <a href="tel:+996554081111">0 554/</a>
                        <a href="tel:+996774081111">0 774/</a>
                        <a href="tel:+996502081111">0 502</a>
                    </div>
                    <div class="number"><a href="tel:+996554081111">
                            08-11-11</a></div>
                </div>
            </div>
        </div>


        <!--        D-abad-->
        <div class="card" style="width: 20rem; text-align: center; background: inherit; border: none">
            <div class="card-body">
                <div class="tel-head">
                    <div class="city"><h5 class="card-title cities">Джалал-Абад </h5>
                    </div>
                    <div class="icon"><a href="https://wa.me/996554083333"><i class="fab fa-whatsapp icons"></i></a>
                    </div>
                </div>
                <div class="tel">
                    <div class="code">
                        <a href="tel:+996554083333">0 554/</a>
                        <a href="tel:+996774083333">0 774/</a>
                        <a href="tel:+996704083333">0 704</a>
                    </div>
                    <div class="number"><a href="tel:+996554083333">
                            08-33-33</a></div>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="navigation">
    <nav class="navbar navbar-expand-lg" style="background: #bfa58c; opacity: 50%">
        <ul class="navbar-nav me-auto mx-auto">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
        </ul>
    </nav>
</div>
<main>

</main>

<footer>

</footer>
</body>
</html>