insert into `food_types` (`name`) values ('sushi'),
                                        ('baked_roll'),
                                        ('snacks'),
                                        ('fried_roll'),
                                        ('cold_roll'),
                                        ('lunch'),
                                        ('dessert'),
                                        ('set'),
                                        ('soup'),
                                        ('cold_drink'),
                                        ('milk_drink'),
                                        ('tea'),
                                        ('coffee'),
                                        ('extra'),
                                        ('other');